### ISSUE TITLE
Using domino for Angular server side rendering

### ISSUE THREAD

**Issue by vikerman** [fgnass/domino#100]
Just opening for discussion/thoughts:

In Angular we currently have an interface through which Angular manipulates the DOM (on server and browser). We want to get rid of this and just use a DOM API on both server and browser. This would also let our users bring in third party libraries to work more seamlessly on the server.

I am prototyping a domino backed DOM implementation for Angular on the server since I found domino to provide good performance while providing the set of DOM APIs that we need.

Are there issues in domino I should be aware of while using it on the server?

**Comment by cscott** [comment]
Not that I know of: we use domino server side for Parsoid here at
wikimania.  Just stick to the modern DOM interfaces, as domino doesn't
support every jot and tittle of the ancient backward compat stuff.  The
README describes the common gotchas I think.  And patches are always
welcome if you find some missing feature.

**Comment by vikerman** [comment]
Thanks! Good to know it's being used in production. Will open individual issues for anything we encounter. Looking forward to collaborating on domino!
