### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by vikerman** [fgnass/domino#103]
Angular 5.0 beta(and beyond) is now switched to using Domino as the DOM implementation on the server - https://github.com/angular/angular/commit/2f2d5f35bd086abeafceabdd5ff9430221b1917f

This means that the when an Angular application asks for the current Document on the server a Domino doc is returned. Further Angular components that work with nativeElement, now get a Domino HTMLElement on the server.

Since Domino does not implement the full DOM spec it would be useful for Angular developers(and I'm guessing other Domino users also) to know during compile time instead of runtime, which subset of the DOM API would work for them when accessing the Document or HTMLElement on the server. This would be the subset they know would be guaranteed to work on both the client and server if their code compiles - instead of erroring out during runtime.

There are two options
1) Switch Domino code to TypeScript from JavaScript. Then have a build step that produces the JS along with the TypeScript type definitions
2) Hand write a separate .d.ts that matches the current Domino implementation and publish it to DefinitelyTyped repo.

1 ) would be the preferred way since that would make it easier to the keep the Type definitions in sync with the current implementation. Please let me know whether you would be open to switching to TypeScript.

**Comment by MarkPieszak** [comment]
@fgnass If you get a chance, it'd be great to have your feedback on this one as it'd be real beneficial to know what's available in the `document` available on the server as Vikram was saying. :)

**Comment by cscott** [comment]
I don't think domino should be rewritten in TypeScript.  I'd accept patches of the form of #2, though.
