### ISSUE TITLE
Error: NotYetImplemented for global[...] = ...  with Angular 5 + Angular Universal

### ISSUE THREAD

**Issue by hekod777** [fgnass/domino#115]
Angular CLI: 1.5.6
Node: 6.13.0
OS: darwin x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/.DS_Store: error
@angular/cli: 1.5.6
@angular/platform-server: 5.2.5
@angular-devkit/build-optimizer: 0.0.40
@angular-devkit/core: 0.2.0
@angular-devkit/schematics: 0.0.50
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.6
@schematics/angular: 0.1.15
@schematics/schematics: 0.0.15
typescript: 2.4.2
webpack-node-externals: 1.6.0
webpack: 3.8.1

------------------------------------------------------------------

I was following this post https://github.com/angular/universal/issues/830 and use these codes in server.ts
```
const domino = require('@angular/platform-server/node_modules/domino');
import { join } from 'path';
import { readFileSync } from 'fs';

const DIST_FOLDER = join(process.cwd(), 'dist');
const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();

const win = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
```

every single `global[...] = ...` line is giving me error not yet implemented error.

Any ideas?

**Comment by cscott** [comment]
Seems to be a problem with Angular, and a solution is offered upstream: https://github.com/angular/universal/issues/830#issuecomment-363277913

**Comment by hekod777** [comment]
tried `const domino = require('@angular/platform-server/node_modules/domino');` solution.

But it didn't work.

**Comment by techtic-maulik** [comment]
I have same issue
