### ISSUE TITLE
Dom Events callback

### ISSUE THREAD

**Issue by lifeart** [fgnass/domino#116]
Hi Felix! I'm want to use `domino` for AsyncDom implementation, demos can be find in https://github.com/lifeart/demo-async-dom, my creepy pseudo dom implementation - https://github.com/lifeart/demo-async-dom/blob/master/react-port/pseudo-dom.js, I'm interesting, how I can easily (painless) integrate my `asyncMessage` for each Dom related call using domino.

**Comment by cscott** [comment]
Is there a W3C or WHATWG spec for the functionality you want?

**Comment by lifeart** [comment]
NVM, it's already working very well. Thank you for response!
