### ISSUE TITLE
ContainerNode removeChildren() leaves parent pointers behind

### ISSUE THREAD

**Issue by clint-tseng** [fgnass/domino#129]
This all came up when trying to run the simple `$("<div/><div/>")` with jQuery (simply bound against a `domino.createWindow()`). There are [various details](https://github.com/jquery/jquery/blob/662083ed7bfea6bad5f9cd4060dab77c1f32aacd/src/manipulation/buildFragment.js) in `buildFragment` in jQueryland that eventually cause the problem, but the essence of what they do is this:

1. Create a document fragment.
2. Create and append a temporary container div to that fragment.
3. Assign the given html as innerHTML on the container div.
4. Grab the created nodes back off the container div.
5. Clear the container div by setting `.textContent = ""`.
6. Clear the fragment by setting `.textContent = ""`.
7. Append each of the created nodes back directly onto the fragment (handwave handwave a bunch of `<script>`-related things that I don't care about).

Step 7 fails for the second child, because setting the container div `.textContent = ""` eventually runs up to ContainerNode removeChildren(), which does the following:

1. Get the first node as the current node.
2. Possibly run a mutateRemove on the root if it exists (doesn't in this case).
3. Set the current node `parentNode = null`.
4. From the current node, fetch `.nextSibling`.
5. If `.nextSibling` exists, repeat from step 2 until no `.nextSibling` exists.

Unfortunately, `.nextSibling` immediately returns `null` if it doesn't have a parent. So only the first node is ever actually touched. This isn't often so big a deal, but eventually the jQuery failure above in step 7 occurs when the span is appended back into the fragment, and one or another (didn't dig deep enough to figure out which) sanity assertion check fails.

I have a code fix that I'll open a PR with as soon as I get these darn tests up and running again and figure out where to put the new test.

**Comment by clint-tseng** [comment]
And the assertion failure is when the span tries to remove from its old context before adding to the new one; it checks its index on its current parent and barfs.

**Comment by cscott** [comment]
Closed via #130
