### ISSUE TITLE
defining viewport width and height

### ISSUE THREAD

**Issue by nblum** [fgnass/domino#131]
is there any possibility to set the size of the viewport like
```
let win = domino.createWindow(template);
win.document.innerWidth = 768;
win.document.innerHeight = 1024;
```

**Comment by cscott** [comment]
I'm not sure what that would do -- domino doesn't contain a layout engine.

**Comment by Vingtoft** [comment]
I also need this.

Use case:
I'm server side rendering an Angular application where I use FlexBox (and of course domino as the server side DOM implementation).
My layout contains several show/hide, which is dependent on the width of the clients viewport.
