### ISSUE TITLE
IE11 support break in version 2.1

### ISSUE THREAD

**Issue by alaingiller** [fgnass/domino#133]
@Angular/platform-server version 7+ use domino 2.1+ which break IE11 support. I need platform-server on UI-side because of caching.

The problem:
NodeList.js contains the following code:
```javascript
var NodeList;
try {
    // Attempt to use ES6-style Array subclass if possible.
    NodeList = require('./NodeList.es6.js');
} catch (e) {
    // No support for subclassing array, return an actual Array object.
    NodeList = require('./NodeList.es5.js');
}

module.exports = NodeList;
```
And on build node will surely support es6 and never go in catch clause. So in final bundle there will be the es6 version with the keyword `class` which cannot be fixed with any polyfill.

Workaround:
- in package.json use `"domino": "<2.1"` (won't work with @Angular/platform-server version 7+)
or
- run this following script in postinstall of package.json (` "postinstall": "node fix-domino.js"`)
```javascript
var fs = require('fs');
fs.readFile('node_modules/domino/lib/NodeList.js', 'utf8', function (err,data) {
	if (err) {
		return console.log(err);
	}
	var result = data.replace('es6', 'es5');

	fs.writeFile('node_modules/domino/lib/NodeList.js', result, 'utf8', function (err) {
		if (err) return console.log(err);
	});
});
```

**Comment by cscott** [comment]
This seems like an angular bug, or a bug in how you are packaging domino for the web.  This doesn't really seem like a bug in domino, which is after all "DOM In NOde".

Can you refile this bug against a more appropriate package?  Obviously I can't merge that workaround postinstall script.

**Comment by CaerusKaru** [comment]
@alaingiller This belongs in [this](https://github.com/angular/universal) repository, please file an issue there with a minimal reproduction repository that we can investigate.

**Comment by alaingiller** [comment]
The root problem is in fact in `ngx-cache`: `@ngx-cache/platform-browser` depend on `@angular/platform-server`. I open a bug there: https://github.com/fulls1z3/ngx-cache/issues/113

**Comment by CaerusKaru** [comment]
@cscott This can be closed
