### ISSUE TITLE
XML Mode?

### ISSUE THREAD

**Issue by acrodrig** [fgnass/domino#56]
While parsing some XML documents, I noticed that domino is having trouble parsing tags that use short notation like:

```xml
<some>
  <one/>
  <two>AAA</two>
</some>
```

In this case it would have trouble with `one`. Is there a setting that allows me to tell domino that I am parsing XML? Or maybe XHTML?

**Comment by cscott** [comment]
Nope.  Domino is an html5 parser.  You want an XML parser.

**Comment by lygstate** [comment]
Are that would be very hard to support for XML? I need a dencent XML parser that can be running in worker.
