### ISSUE TITLE
Attr interface is missing .nodeValue and .textContent properties

### ISSUE THREAD

**Issue by JLRishe** [fgnass/domino#70]
As indicated in the [spec section linked from this project's README](https://dom.spec.whatwg.org/#interface-attr). The _Attr_ interface in DOM4 is supposed to have a `.nodeValue` and a `.textContent` property as legacy aliases of the `.value` property, but these are not supported in this library:

    var domino = require('domino');
 
    var document = domino.createDocument('<h1 class="hello">Hello world</h1>');
 
    var h1 = document.querySelector('h1');
    var classAttr = h1.attributes.item(0);

    console.log('value is:' + classAttr.value);
    console.log('nodeValue is:' + classAttr.nodeValue);
    console.log('textContent is:' + classAttr.textContent);

**Comment by cscott** [comment]
The README for this project (domino) notes that it intentionally "doesn't implement any properties which have been deprecated in HTML5."

Why not just fix your code to use the proper `.value` accessor?

**Comment by JLRishe** [comment]
> Why not just fix your code to use the proper  .value  accessor?

That's precisely what I have done now, but the problem is that I'm not personally using domino; I'm maintaining a library that simply expects DOM-compliant inputs, and someone trying to use domino with my library encountered an error and reported it as a [bug in my library](https://github.com/goto100/xpath/issues/32). Things like this are bound to happen if the domino is not DOM compliant, but if your policy is to not support deprecated properties, then I guess that's fair enough.

**Comment by cscott** [comment]
://github.com/goto100/xpath/commit/ca913d9978a8c4400cb17195bc9ff725e194b5a6
seems like the right fix.  But you think there are other places your
library accesses one of these deprecated properties of Attr?

The stated policy of domino is to not support deprecated properties.  As a
maintainer, I've got some wiggle room, so I'm trying to figure out whether
there is indeed a compelling reason to support these (or not).
