### ISSUE TITLE
request to add Time functions to domino, because JQuery depends on them

### ISSUE THREAD

**Issue by ArndBrugman** [fgnass/domino#72]
JQuery added code that relies on window having the functions of time:
setTimeout, clearTimeout, setInterval, clearInterval

window.setTimeout is missing in JQuery when I rely on domino in nodejs.

Could you please add these to domino, so they will be defined in window object and my project based on JQUery and domino is functioning again?

Thx.

**Comment by mgol** [comment]
Since `domino` is made just for node it seems that just assigning `window.setTimeout = setTimeout` etc. should be enough.

For reference, this issue has more details: https://github.com/jquery/jquery/issues/2906

**Comment by cscott** [comment]
To be precise, this is referring to methods on the Window object created by domino.  I'll take a look at this.

**Comment by ArndBrugman** [comment]
In
domino/lib/Window.js 
add before line 15:

```
    this.setTimeout = setTimeout;
    this.clearTimeout = clearTimeout;
    this.setInterval = setInterval;
    this.clearInterval = clearInterval;
```

Test and Close ;)
