### ISSUE TITLE
Allow building document fragments

### ISSUE THREAD

**Issue by pimterry** [fgnass/domino#73]
It'd be really useful to be able to build document fragments, not only whole HTML documents. Is that possible? This is a feature that's common in parse-side libraries, like [Parse5](https://github.com/inikulin/parse5/wiki/Documentation#parse5+parseFragment), which leads me to think it's not a spec issue, just that it hasn't been implemented yet.

More specifically, it'd be useful to be able to do something like:

```javascript
var doc = domino.createDocumentFragment("<div></div>");
doc.childNodes[0].innerHTML = "Hi";
console.log(doc.documentElement.outerHTML);  // "<div>Hi</div>";
```

Currently, if you try to do this (with `createDocument`) you get extra <html>, <head> and <body> tags wrapped around your content.

Is that possible? I'd be happy to have a go at implementing it, if you can point me in the right direction.

**Comment by cscott** [comment]
This is implemented, using the standard DOM interfaces, AFAIK.  In fact, the exact code you've writte above works in domino, as far as I can tell.  Can you describe the problem you see more exactly?

**Comment by pimterry** [comment]
`domino.createDocumentFragment` doesn't exist, so I'm pretty sure that example doesn't work. `domino.createDocument` does of course, but adds in extra wrapping `<html>`, `<head>` and `<body>` tags, which is what I'm trying to avoid.

Just to be clear: my goal is to take a chunk of HTML string that doesn't necessarily represent a full document, parse it into dom nodes, make changes through the dom api, and then transform the result back into a string. I think that's a pretty common use case, but I can't see any easy way to do that with domino right now.

Within the domino dom implementation you can currently build actual 'official' [DocumentFragments](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) with `new domino.impl.Document().createDocumentFragment()`, but that doesn't really flow off the tongue, and the built in DocumentFragment API is  [remarkably difficult](http://stackoverflow.com/questions/9284117/inserting-arbitrary-html-into-a-documentfragment) to add HTML to in string form or to [get an HTML string back out from](http://stackoverflow.com/questions/17230106/how-to-convert-a-document-fragment-to-string-content-in-javascript).

It looks like the best approach to do this in a browser normally is to create a `<template>` tag, put the content in there directly and use `template.content` to get a fragment back out, according to [stackoverflow](http://stackoverflow.com/a/25214113/68051). Alternatively you can create the template tag, and then create a document fragment, and add the template tag as the root, which is what [parse5 does](https://github.com/inikulin/parse5/blob/3c195ec374422497fdce1f98528dab9e7ebbeb9b/lib/parser/index.js#L378-L406). Any enthusiasm an top-level API along these lines to domino? This would require `<template>` support, but you could get pretty close with the parse5 approach using just a `<div>`.

That would be a reasonable solution for creation of standalone HTML fragments. Turning them back into strings would still be a little messy though, although doable. parse5 here provides `parse5.serialize`, as a solution for this generally, which might be an useful extension?

**Comment by cscott** [comment]
As you note, `document.createDocumentFragment()` exists, which is the standard constructor.  Historically domino has avoided creating new bespoke top-level API, in favor of using standardized methods.  The next version of domino does support the `<template>` tag, fwiw.

domino generally provides `outerHTML` as a serialization method, even on objects (like `Document`) which don't have this in the WHATWG spec.

**Comment by fgnass** [comment]
A fairly easy solution should be to implement the setter for `DocumentFragment.innerHTML` which if I remember it correctly used to throw a _not yet implemented_ error.

**Comment by pimterry** [comment]
Ah, ok, makes sense. Great to hear `<template>` is coming in soon!

> A fairly easy solution should be to implement the setter for DocumentFragment.innerHTML which if I remember it correctly used to throw a not yet implemented error.

Currently fragment.innerHTML doesn't exist at all, probably because it also doesn't exist (as a getter or setter) in browsers either. DocumentFragments have a pretty terrible API.

> domino generally provides outerHTML as a serialization method, even on objects (like Document) which don't have this in the WHATWG spec.

Not on document fragments interestingly. That'd be a helpful addition! That's actually probably the most important part from my point of view. In a browser context if you want to serialize a fragment you have to use `XMLSerializer`, but of course that's not a built-in in Node, so it gets quite a bit more difficult.

I think this means, if I want to do this, I need to do:

```javascript
var domino = require("domino");

var document = domino.createDocument()
var template = document.createElement("template");
template.innerHTML = "<div></div>";

var fragment = template.content;
// Make whatever changes I want

console.log(fragment.outerHTML);
```

That's manageable from my point of view. This is once template support comes in, and assuming you're happy to add outerHTML to document fragments?

**Comment by cscott** [comment]
Hm -- although `<template>` is a instance of `HTMLTemplateElement` which is a `HTMLElement` which is an `Element` and https://w3c.github.io/DOM-Parsing/#attributes defines `innerHTML`/`outerHTML` on `Element`, some specification work appears undone -- since as I read the current specs when `innerHTML` is set (as in the fourth line in your example) the created nodes are adopted into the template node directly, not the associated document fragment, and seem to belong to the wrong document. :(

**Comment by cscott** [comment]
The problem with the `innerHTML` of `<template>` seems to be: https://github.com/w3c/DOM-Parsing/issues/1

**Comment by cscott** [comment]
Incidentally, in your example, you can use `template.innerHTML` as a standards-compliant alternative to `fragment.outerHTML`.
