### ISSUE TITLE
document.location

### ISSUE THREAD

**Issue by gagern** [fgnass/domino#75]
Accoding to [MDC](https://developer.mozilla.org/en-US/docs/Web/API/Document/location) and [WHATWG](https://html.spec.whatwg.org/multipage/browsers.html#dom-document-location), there should be a `document.location` attribute mirroring `window.location`. Quoting the latter:

> The `location` attribute of the `Document` interface must return the `Location` object for that `Document` object's global object, if it has a [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#concept-document-bc), and null otherwise.

I found out that [GWT-compiled code needs this](https://github.com/gagern/CindyJS/commit/d41baa2540790bcfff000d428f108bf62e950b72).

**Comment by cscott** [comment]
`window.location` is a bit of a hack in domino, but we can certainly make `document.location` proxy to it.  I think we'd need to audit how domino handles the "browsing context" for a document, and make sure it matches the spec.  Patches welcome!
