### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by gagern** [fgnass/domino#76]
While [trying to get GWT-compiled code to execute in a domino environment](https://github.com/gagern/CindyJS/commit/d41baa2540790bcfff000d428f108bf62e950b72), I noticed that the `iframe` element is lacking some required properties. It should provide a `contentWindow` and an associated `contentDocument`. These could be set up by `domino.createWindow`, but I think it would be better if there were some kind of configurable factory, so that users could add additional steps, e.g. turning the window into a [vm context](https://nodejs.org/api/vm.html), modifying the `navigator` property or installing a `mutationHandler`.

**Comment by cscott** [comment]
Is this related to the missing "browser context" support from issue #75?

**Comment by gagern** [comment]
I don't think the two items are related, no.
