### ISSUE TITLE
(elem instanceof HTMLElement) is false

### ISSUE THREAD

**Issue by GegeFR** [fgnass/domino#85]
Hi, I'm trying to run code in domino for server-side rendering of an existing app that uses "instanceof" .

Up to now I've been testing with jsdom in Node.js.

I'd like to do my rendering in Nashorn and I wanted to try Domino since it doesn't seems to be tightly bound to Node.js, however the following code (I guess it's valid for all elements) : 
```
var btn = document.createElement("BUTTON");
console.log(btn instanceof HTMLElement);
```

returns `false` where it returns `true` in browsers or in jsdom (at least in Node.js).

I also had to manually run the htmlelts.js in order to have the "HTMLElement" class available.

**Comment by cscott** [comment]
The following prints `true` for me, in node:
```
var domino = require('./');
var document = domino.createDocument('');
var btn = document.createElement('BUTTON');
console.log(btn instanceof domino.impl.HTMLElement);
```
